use z511s24vpawar2;

#Exercise 1 A

CREATE TABLE SoftwarePackage(
SPID CHAR(2) NOT NULL,
SPName VARCHAR(30) NOT NULL,
PRIMARY KEY (SPID)
);

CREATE TABLE Employee (
EmpID CHAR(2) NOT NULL,
EmpName VARCHAR(25) NOT NULL,
PRIMARY KEY (EmpID)
);

CREATE TABLE Computer(
CompID CHAR(2) NOT NULL,
MaintEmpID CHAR(2) NOT NULL,
AssignedToEmpID CHAR(2) NOT NULL,
CompModel VARCHAR(30) NOT NULL,
CompMake VARCHAR(30) NOT NULL,
PRIMARY KEY (CompID),
FOREIGN KEY (MaintEmpID)
	REFERENCES Employee (EmpID),
FOREIGN KEY (AssignedToEmpID)
	REFERENCES Employee (EmpID)
);

CREATE TABLE EmpSkill (
EmpID CHAR(2) NOT NULL,
EmpSkill VARCHAR(25) NOT NULL,
PRIMARY KEY (EmpSkill, EmpID),
FOREIGN KEY (EmpID)
	REFERENCES Employee (EmpID)
);

CREATE TABLE UseCertified(
SPID CHAR(2) NOT NULL,
EmpID CHAR(2) NOT NULL,
PRIMARY KEY (SPID, EmpID),
FOREIGN KEY (SPID)
	REFERENCES SoftwarePackage (SPID),
FOREIGN KEY (EmpID)
	REFERENCES Employee (EmpID)
);

CREATE TABLE InstalledAt(
SPID CHAR(2) NOT NULL,
CompID CHAR(2) NOT NULL,
DateOfInstall DATE NOT NULL,
PRIMARY KEY (SPID, CompID),
FOREIGN KEY (SPID)
	REFERENCES SoftwarePackage (SPID),
FOREIGN KEY (CompID)
	REFERENCES Computer (CompID)
);

#Exercise 1 B

DROP TABLE InstalledAt;
DROP TABLE UseCertified;
DROP TABLE EmpSkill;
DROP TABLE Computer;
DROP TABLE Employee;
DROP TABLE SoftwarePackage;
